# - Try to find OpenGL ES
# Once done this will define
#
#  OPENGLES_FOUND        - system has OpenGL ES
#  EGL_FOUND             - system has EGL
#  OPENGLES_INCLUDE_DIR  - the GLES include directory
#  OPENGLES_LIBRARIES    - Link these to use OpenGL ES and EGL

IF (APPLE)
    CREATE_SEARCH_PATHS(/Developer/Platforms)
    FINDPKG_FRAMEWORK(OpenGLES)
    SET(OPENGLES_gles_LIBRARY "-framework OpenGLES")

ELSE (APPLE)
    FIND_PATH(OPENGLES_INCLUDE_DIR GLES/gl.h)
    FIND_LIBRARY(OPENGLES_gles_LIBRARY GLES_CM)

    IF (OPENGLES_gles_LIBRARY)
        FIND_PATH(EGL_INCLUDE_DIR GLES/egl.h)
        FIND_LIBRARY(EGL_egl_LIBRARY EGL)

        IF (NOT X11_FOUND)
            INCLUDE(FindX11)
        ENDIF (NOT X11_FOUND)
        IF (X11_FOUND)
            SET (OPENGLES_LIBRARIES ${X11_LIBRARIES})
        ENDIF (X11_FOUND)
    ENDIF (OPENGLES_gles_LIBRARY)
ENDIF (APPLE)

IF (OPENGLES_gles_LIBRARY)
    SET(OPENGLES_LIBRARIES ${OPENGLES_gles_LIBRARY} ${OPENGLES_LIBRARIES})
    SET(OPENGLES_FOUND "YES")
ENDIF (OPENGLES_gles_LIBRARY)

IF (EGL_egl_LIBRARY)
    SET(EGL_LIBRARIES ${EGL_egl_LIBRARY} ${EGL_LIBRARIES})
    SET(EGL_FOUND "YES")
ENDIF (EGL_egl_LIBRARY)

MARK_AS_ADVANCED(
    OPENGLES_INCLUDE_DIR
    OPENGLES_gles_LIBRARY
    EGL_INCLUDE_DIR
    EGL_egl_LIBRARY
)

